name: CCT-i bpo
favicon: null
layout_spectrum: 0.03645132784731686
typography_spectrum: 0.13083864958025515
title: 'really cool tools... seamless, transparent and totally connected'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5a8fd3'
    - '#192c33'
    - '#d9e9f9'
    - '#8ec0f1'
    - '#66704a'
  brandStrength: 1
  lightness: 0.5038585877045989
  saturation: 1
  rhythmicContrast: 1
purpose: []
