name: CCT-i bpo
favicon: null
layout_spectrum: 0.03645132784731686
typography_spectrum: 0.13083864958025515
title: 'really cool tools... seamless, transparent and totally connected'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3464a6'
    - '#6c9dc8'
    - '#afc4d9'
    - '#23390b'
    - '#deebf1'
  brandStrength: 0.5
  lightness: 0.5038585877045989
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
