name: CCT-i bpo
favicon: null
layout_spectrum: 0.03645132784731686
typography_spectrum: 0.13083864958025515
title: 'really cool tools... seamless, transparent and totally connected'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.8543386571109295
  lightness: 0.5038585877045989
  saturation: 0.5642593635711819
  rhythmicContrast: 0.6519505346659571
purpose: []
